"""Integration tests: run the xlsx import against the shipped sample workbook.

The sample is generated by ``backend/scripts/generate_sample_workbook.py`` and
is deliberately structured like the private research workbook: both tab layout
variants plus one unfinished tab whose metric block is nothing but Excel error
sentinels. That last one is the point — the importer has to log it and carry on
rather than fail the run.

Unlike :mod:`tests.integration.test_import_real_xlsx`, these run everywhere, so
the import paths stay covered on a fresh clone.

Requires the dev_db Postgres server
(port 55432, ``bash backend/scripts/dev_db.sh``).
"""

from __future__ import annotations

import pytest
from sqlalchemy import func, select

from app.models import ImportRun, System, Trade
from app.services.import_service import run_xlsx_import
from tests.paths import SAMPLE_XLSX

pytestmark = pytest.mark.integration

XLSX_PATH = str(SAMPLE_XLSX)

# Fixed by the generator's seed; see SPECS in generate_sample_workbook.py.
TABS_TOTAL = 6
COMPLETE_SYSTEMS = 5
TOTAL_TRADES = 140 + 190 + 240 + 120 + 88


def test_sample_workbook_is_present():
    assert SAMPLE_XLSX.is_file(), (
        f"sample workbook missing at {SAMPLE_XLSX} — regenerate it with "
        "`python backend/scripts/generate_sample_workbook.py`"
    )


def test_import_sample_workbook_statistics(db_session):
    run = run_xlsx_import(db_session, XLSX_PATH)

    assert run.tabs_total == TABS_TOTAL
    assert (
        run.systems_complete + run.systems_incomplete + run.tabs_skipped
        == TABS_TOTAL
    )
    assert run.systems_complete == COMPLETE_SYSTEMS
    assert run.trades_imported == TOTAL_TRADES
    assert len(run.tab_results) == TABS_TOTAL

    db_trades = db_session.execute(select(func.count(Trade.id))).scalar_one()
    assert db_trades == TOTAL_TRADES


def test_unfinished_tab_is_reported_not_fatal(db_session):
    """A tab full of ``#DIV/0!`` must not take the run down with it."""
    run = run_xlsx_import(db_session, XLSX_PATH)

    incomplete = [
        r for r in run.tab_results if r["status"] in ("incomplete", "skipped")
    ]
    assert len(incomplete) == 1
    assert incomplete[0]["tab"] == "VP-H1-906.wip"

    # ...and the other five still imported.
    assert run.systems_complete == COMPLETE_SYSTEMS


def test_both_layout_variants_parse(db_session):
    """Variant B (name in B3, shifted trade columns) must import like variant A."""
    run_xlsx_import(db_session, XLSX_PATH)

    variant_b = db_session.execute(
        select(System).where(System.name == "BB-M5-905.v2")
    ).scalar_one_or_none()
    assert variant_b is not None

    trades = db_session.execute(
        select(func.count(Trade.id)).where(Trade.system_id == variant_b.id)
    ).scalar_one()
    assert trades == 88


def test_import_is_idempotent(db_session):
    run1 = run_xlsx_import(db_session, XLSX_PATH)
    systems_after_1 = db_session.execute(select(func.count(System.id))).scalar_one()
    trades_after_1 = db_session.execute(select(func.count(Trade.id))).scalar_one()

    run2 = run_xlsx_import(db_session, XLSX_PATH)
    systems_after_2 = db_session.execute(select(func.count(System.id))).scalar_one()
    trades_after_2 = db_session.execute(select(func.count(Trade.id))).scalar_one()

    assert systems_after_1 == systems_after_2
    assert trades_after_1 == trades_after_2
    assert run1.trades_imported == run2.trades_imported
    assert run1.tabs_total == run2.tabs_total == TABS_TOTAL


def test_auto_trades_survive_reimport(db_session):
    """Re-import replaces manual (xlsx) trades but must never touch auto ones."""
    run_xlsx_import(db_session, XLSX_PATH)

    system = db_session.execute(select(System).limit(1)).scalar_one()
    auto = Trade(system_id=system.id, r_value=1.5, source="auto")
    db_session.add(auto)
    db_session.commit()
    auto_id = auto.id

    manual_before = db_session.execute(
        select(func.count(Trade.id)).where(
            Trade.system_id == system.id, Trade.source == "manual"
        )
    ).scalar_one()

    run_xlsx_import(db_session, XLSX_PATH)

    still_there = db_session.execute(
        select(Trade).where(Trade.id == auto_id)
    ).scalar_one_or_none()
    assert still_there is not None
    assert still_there.source == "auto"

    manual_after = db_session.execute(
        select(func.count(Trade.id)).where(
            Trade.system_id == system.id, Trade.source == "manual"
        )
    ).scalar_one()
    assert manual_after == manual_before


def test_two_import_runs_recorded(db_session):
    run_xlsx_import(db_session, XLSX_PATH)
    run_xlsx_import(db_session, XLSX_PATH)

    runs = db_session.execute(select(ImportRun)).scalars().all()
    assert len(runs) == 2
    for run in runs:
        assert len(run.tab_results) == TABS_TOTAL
