"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-07-10 15:08:23.612142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('tabs_total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('systems_complete', sa.Integer(), server_default='0', nullable=False),
    sa.Column('systems_incomplete', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tabs_skipped', sa.Integer(), server_default='0', nullable=False),
    sa.Column('trades_imported', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tab_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('systems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=True),
    sa.Column('timeframe', sa.String(length=16), nullable=True),
    sa.Column('status', sa.Enum('backtest', 'live_testing', 'active', 'retired', name='system_status', native_enum=False), server_default='backtest', nullable=False),
    sa.Column('entry_rule', sa.Text(), nullable=True),
    sa.Column('sl_rule', sa.Text(), nullable=True),
    sa.Column('tp_rule', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('import_status', sa.Enum('complete', 'incomplete', 'skipped', name='import_status', native_enum=False), server_default='incomplete', nullable=False),
    sa.Column('reported_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('trade_datetime', sa.DateTime(), nullable=True),
    sa.Column('zone', sa.String(length=64), nullable=True),
    sa.Column('timeframe', sa.String(length=16), nullable=True),
    sa.Column('entry', sa.Float(), nullable=True),
    sa.Column('sl', sa.Float(), nullable=True),
    sa.Column('exit', sa.Float(), nullable=True),
    sa.Column('direction', sa.Enum('long', 'short', name='trade_direction', native_enum=False), nullable=True),
    sa.Column('r_value', sa.Float(), nullable=True),
    sa.Column('win_loss', sa.Enum('win', 'loss', 'draw', name='trade_win_loss', native_enum=False), nullable=True),
    sa.Column('source', sa.Enum('manual', 'auto', name='trade_source', native_enum=False), server_default='manual', nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trades_system_id_trade_datetime', 'trades', ['system_id', 'trade_datetime'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trades_system_id_trade_datetime', table_name='trades')
    op.drop_table('trades')
    op.drop_table('systems')
    op.drop_table('import_runs')
    # ### end Alembic commands ###
