"""live_trading

Revision ID: 0007
Revises: 0006
Create Date: 2026-07-24 13:02:48.876179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0007'
down_revision: Union[str, None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('asset_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('asset', sa.String(length=32), nullable=False),
    sa.Column('entry_fee_pct', sa.Float(), nullable=False),
    sa.Column('exit_fee_pct', sa.Float(), nullable=False),
    sa.Column('min_position_size', sa.Float(), nullable=False),
    sa.Column('leverage_buffer', sa.Float(), server_default='0.1', nullable=False),
    sa.Column('upside_deviation_allowed_pct', sa.Float(), server_default='0.05', nullable=False),
    sa.Column('downside_deviation_allowed_pct', sa.Float(), server_default='0.05', nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue_id', 'asset', 'valid_from', name='uq_asset_settings_version')
    )
    op.create_table('live_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('asset_setting_id', sa.Integer(), nullable=True),
    sa.Column('asset', sa.String(length=32), nullable=True),
    sa.Column('stage', sa.Enum('setup_sighted', 'risk_calculated', 'order_placed', 'entry_filled', 'running', 'closed', 'cancelled', name='live_trade_stage', native_enum=False), server_default='setup_sighted', nullable=False),
    sa.Column('direction', sa.Enum('long', 'short', name='live_trade_direction', native_enum=False), nullable=True),
    sa.Column('entry_order_type', sa.Enum('market', 'limit', name='entry_order_type', native_enum=False), nullable=True),
    sa.Column('planned_entry', sa.Float(), nullable=True),
    sa.Column('planned_stop', sa.Float(), nullable=True),
    sa.Column('actual_entry', sa.Float(), nullable=True),
    sa.Column('actual_stop', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('position_size_coins', sa.Float(), nullable=True),
    sa.Column('position_size_notional', sa.Float(), nullable=True),
    sa.Column('leverage', sa.Float(), nullable=True),
    sa.Column('risk_usd', sa.Float(), nullable=True),
    sa.Column('risk_pct', sa.Float(), nullable=True),
    sa.Column('risk_modifier', sa.Float(), nullable=True),
    sa.Column('expected_loss', sa.Float(), nullable=True),
    sa.Column('realized_pnl_usd', sa.Float(), nullable=True),
    sa.Column('r_value', sa.Float(), nullable=True),
    sa.Column('win_loss', sa.Enum('win', 'loss', 'break_even', name='live_win_loss', native_enum=False), nullable=True),
    sa.Column('deviation_pct', sa.Float(), nullable=True),
    sa.Column('fees_paid', sa.Float(), nullable=True),
    sa.Column('funding_paid', sa.Float(), nullable=True),
    sa.Column('slippage', sa.Float(), nullable=True),
    sa.Column('balance_after', sa.Float(), nullable=True),
    sa.Column('portfolio_size_at_creation', sa.Float(), nullable=True),
    sa.Column('snap_entry_fee_pct', sa.Float(), nullable=True),
    sa.Column('snap_exit_fee_pct', sa.Float(), nullable=True),
    sa.Column('snap_min_position_size', sa.Float(), nullable=True),
    sa.Column('snap_leverage_buffer', sa.Float(), nullable=True),
    sa.Column('snap_upside_deviation_allowed_pct', sa.Float(), nullable=True),
    sa.Column('snap_downside_deviation_allowed_pct', sa.Float(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('setup_sighted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('risk_calculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('order_placed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entry_filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('running_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('rules_followed', sa.Boolean(), nullable=True),
    sa.Column('chart_url', sa.String(length=512), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_setting_id'], ['asset_settings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_live_trades_stage', 'live_trades', ['stage'], unique=False)
    op.create_index('ix_live_trades_system_id', 'live_trades', ['system_id'], unique=False)
    op.create_table('account_balance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('change_type', sa.Enum('initial', 'trade_close', 'manual', name='account_change_type', native_enum=False), server_default='manual', nullable=False),
    sa.Column('live_trade_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('as_of', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['live_trade_id'], ['live_trades.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # --- Seeds ---
    # One default venue plus one asset-settings version. The fee rates are the
    # venue's published maker/taker tiers; adjust them under Settings.
    op.execute(
        "INSERT INTO venues (name, notes) VALUES ('CEX', 'Standard-Venue (Seed)')"
    )
    op.execute(
        """
        INSERT INTO asset_settings
            (venue_id, asset, entry_fee_pct, exit_fee_pct, min_position_size,
             leverage_buffer, upside_deviation_allowed_pct,
             downside_deviation_allowed_pct, valid_from)
        SELECT id, 'DEFAULT', 0.000144, 0.000432, 0.00001, 0.1, 0.05, 0.05,
               '2000-01-01 00:00:00+00'
        FROM venues WHERE name = 'CEX'
        """
    )
    # Placeholder starting balance. Correct it in the UI under Settings, or via
    # POST /account/balance, before recording any live trade.
    op.execute(
        "INSERT INTO account_balance (balance, change_type, note) "
        "VALUES (1000.00, 'initial', 'Placeholder starting balance')"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_balance')
    op.drop_index('ix_live_trades_system_id', table_name='live_trades')
    op.drop_index('ix_live_trades_stage', table_name='live_trades')
    op.drop_table('live_trades')
    op.drop_table('asset_settings')
    op.drop_table('venues')
    # ### end Alembic commands ###
