"""asset_granularity

Revision ID: 0008
Revises: 0007
Create Date: 2026-07-24 16:42:36.856607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0008'
down_revision: Union[str, None] = '0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_settings', sa.Column('max_leverage', sa.Float(), nullable=True))
    op.add_column('asset_settings', sa.Column('leverage_step', sa.Float(), server_default='1.0', nullable=False))
    op.add_column('asset_settings', sa.Column('min_order_value_usd', sa.Float(), nullable=True))
    op.add_column('live_trades', sa.Column('implicit_leverage', sa.Float(), nullable=True))
    op.add_column('live_trades', sa.Column('exchange_leverage', sa.Float(), nullable=True))
    op.add_column('live_trades', sa.Column('snap_max_leverage', sa.Float(), nullable=True))
    op.add_column('live_trades', sa.Column('snap_leverage_step', sa.Float(), nullable=True))
    op.add_column('live_trades', sa.Column('snap_min_order_value_usd', sa.Float(), nullable=True))
    op.add_column('systems', sa.Column('asset', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###

    # --- Seeds (Phase 7.1): echte Hyperliquid-Marktdaten ---
    # Quelle: Hyperliquid Info-API (POST /info {"type":"meta"}), abgefragt
    # 2026-07-24: Lot-Size = 10^-szDecimals, max_leverage ganzzahlig je Asset.
    # Leverage ist laut Doku nur ganzzahlig einstellbar (leverage_step = 1),
    # Mindest-Ordervolumen 10 USDC.
    op.execute("UPDATE asset_settings SET min_order_value_usd = 10.0 WHERE min_order_value_usd IS NULL")
    # Die geseedete Standard-Venue trägt ab jetzt echte Hyperliquid-Grenzen —
    # nur umbenennen, wenn sie noch der unveränderte Seed ist.
    op.execute("UPDATE venues SET name = 'Hyperliquid' WHERE name = 'CEX'")

    # (asset, lot_size, max_leverage) — szDecimals aus der Info-API
    assets = [
        ('BTC', 0.00001, 40),
        ('ETH', 0.0001, 25),
        ('SOL', 0.01, 20),
        ('DOT', 0.1, 10),
        ('XMR', 0.001, 5),
        ('AVAX', 0.01, 10),
        ('LINK', 0.1, 10),
        ('DOGE', 1.0, 10),
    ]
    for name, lot, maxlev in assets:
        op.execute(
            f"""
            INSERT INTO asset_settings
                (venue_id, asset, entry_fee_pct, exit_fee_pct, min_position_size,
                 leverage_buffer, upside_deviation_allowed_pct,
                 downside_deviation_allowed_pct, max_leverage, leverage_step,
                 min_order_value_usd, valid_from)
            SELECT v.id, '{name}', 0.000144, 0.000432, {lot}, 0.1, 0.05, 0.05,
                   {maxlev}, 1.0, 10.0, '2000-01-01 00:00:00+00'
            FROM venues v
            WHERE v.id = (SELECT MIN(id) FROM venues)
              AND NOT EXISTS (
                    SELECT 1 FROM asset_settings s
                    WHERE s.venue_id = v.id AND s.asset = '{name}'
              )
            """
        )


def downgrade() -> None:
    op.execute(
        "DELETE FROM asset_settings WHERE asset IN "
        "('BTC','ETH','SOL','DOT','XMR','AVAX','LINK','DOGE')"
    )
    op.execute("UPDATE venues SET name = 'CEX' WHERE name = 'Hyperliquid'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('systems', 'asset')
    op.drop_column('live_trades', 'snap_min_order_value_usd')
    op.drop_column('live_trades', 'snap_leverage_step')
    op.drop_column('live_trades', 'snap_max_leverage')
    op.drop_column('live_trades', 'exchange_leverage')
    op.drop_column('live_trades', 'implicit_leverage')
    op.drop_column('asset_settings', 'min_order_value_usd')
    op.drop_column('asset_settings', 'leverage_step')
    op.drop_column('asset_settings', 'max_leverage')
    # ### end Alembic commands ###
